import React from 'react';

export const AnalysisQualityScore: React.FC<{ assessment?: any }> = ({ assessment }) => {
  const q = assessment || {}, checked = ['verified', 'partially_verified'].includes(q.status);
  const accuracy = q.accuracy_assessment || {};
  const scored = checked && ['verification_evidence_v1', 'verification_evidence_v2'].includes(q.score_method?.id) && Number.isFinite(q.score) && q.score >= 0 && q.score <= 100;
  const fmt = (value: number) => value.toLocaleString('vi-VN', { maximumFractionDigits: 1 });
  const measured = accuracy.status === 'measured' && Number.isFinite(accuracy.accuracy_pct) && accuracy.reference_count > 0 && accuracy.reference_source;
  const checks = q.verification_checks?.length ? q.verification_checks : q.components || [];
  const groups = [['Đã thực hiện', q.completed], ['Chưa thực hiện', q.missing], ['Chưa thể xác minh', q.unverified], ['Giới hạn dữ liệu', q.limitations]];
  const item = (i: any) => <li key={i.id} className="leading-relaxed">{i.label}{i.evidence_refs?.[0] && <a className="text-blue-600 ml-2 whitespace-nowrap" href={`#evidence-${encodeURIComponent(i.evidence_refs[0])}`}>Đối chiếu ↗</a>}</li>;
  const status = (value: string) => ({ passed: 'Đạt', partial: 'Chưa đầy đủ', failed: 'Chưa đạt', not_applicable: 'Không áp dụng' }[value] || 'Chưa kiểm tra');
  return <section data-analysis-quality aria-label="Kiểm chứng và độ chính xác" className="rounded-2xl border border-slate-200 bg-white p-5 space-y-4">
    <div className="flex items-start justify-between gap-4"><div><h3 className="text-sm font-semibold text-slate-900">Kiểm chứng &amp; độ chính xác</h3><p className="text-xs text-slate-500 mt-1 leading-relaxed">Các kiểm tra dưới đây phát hiện thiếu phạm vi, sai phép tính và dữ liệu trình bày. Tỷ lệ kiểm tra đạt không phải xác suất AI trả lời đúng.</p></div><strong className="text-sm text-slate-800 text-right">{q.status === 'verified' ? 'Qua kiểm tra nội bộ' : checked ? 'Còn phần chưa đạt' : 'Chưa kiểm chứng'}</strong></div>
    {scored && <div className="rounded-xl bg-slate-50 p-4 space-y-2"><div className="flex justify-between items-center gap-4"><h4 className="text-sm font-semibold text-slate-800">Điểm kiểm chứng tổng</h4><strong className="text-2xl text-slate-900">{fmt(q.score)}/100</strong></div><div role="progressbar" aria-label="Điểm kiểm chứng tổng" aria-valuemin={0} aria-valuemax={100} aria-valuenow={q.score} className="h-2 rounded-full bg-slate-200 overflow-hidden"><div className="h-full bg-blue-500" style={{ width:`${q.score}%` }} /></div><p className="text-xs text-slate-600">{q.score_method.interpretation}{q.score_method.unmeasured_points > 0 ? ` Còn ${fmt(q.score_method.unmeasured_points)} điểm đối chứng độc lập chưa được xác minh.` : ''}</p><details className="text-xs text-slate-600"><summary className="cursor-pointer font-medium">Công thức và phân bổ điểm</summary><p className="mt-2 leading-relaxed">{q.score_method.formula}</p><ul className="mt-2 space-y-1">{(q.score_breakdown || []).map((p: any) => <li key={p.id} className="flex justify-between gap-3"><span>{p.label}{p.status === 'not_measured' ? ' · Chưa đo' : p.status === 'not_applicable' ? ' · Không áp dụng' : ''}</span><span>{fmt(p.earned_points)}/{fmt(p.possible_points)}</span></li>)}</ul></details></div>}
    <div className="grid grid-cols-1 md:grid-cols-2 gap-3 text-xs">
      <div className="rounded-xl bg-slate-50 p-3"><h4 className="font-semibold text-slate-800">Độ chính xác đối chứng: {measured ? `${accuracy.accuracy_pct}%` : 'Chưa đo'}</h4><p className="text-slate-500 mt-1 leading-relaxed">{measured ? `${accuracy.matched_count}/${accuracy.reference_count} kết quả khớp đối chứng: ${accuracy.reference_source}. Chỉ áp dụng cho các kết quả được kiểm tra.` : accuracy.reason || 'Chưa có đáp án đối chứng độc lập cho yêu cầu này; kiểm tra nội bộ chưa chứng minh dữ liệu nguồn đúng hoặc AI hiểu đúng toàn bộ câu hỏi.'}</p></div>
      <div className="rounded-xl bg-slate-50 p-3"><h4 className="font-semibold text-slate-800">Xác suất trả lời đúng: Chưa hiệu chuẩn</h4><p className="text-slate-500 mt-1 leading-relaxed">{q.confidence_reason || 'Cần đánh giá trên tập câu hỏi có đáp án chuẩn độc lập trước khi công bố xác suất tin cậy.'}</p></div>
    </div>
    {!checked && <p className="text-xs text-slate-600">{q.reason || 'Chưa đủ metadata để kiểm chứng.'}</p>}
    {!!checks.length && <div className="grid grid-cols-1 md:grid-cols-2 gap-3">{checks.map((c: any) => <div key={c.id} className="rounded-xl border border-slate-100 p-3 text-xs"><div className="flex justify-between gap-2 font-medium text-slate-800"><span>{c.label}</span><span className="whitespace-nowrap">{Number.isInteger(c.total) && c.total > 0 ? `${c.passed}/${c.total} đạt` : status(c.status)}</span></div><p className="text-slate-500 mt-1 leading-relaxed">{c.summary}</p></div>)}</div>}
    {groups.some(([, items]) => items?.length) && <div className="grid grid-cols-1 md:grid-cols-2 gap-5 text-xs text-slate-600">{groups.map(([label, items]) => !!items?.length && <div key={label}><h4 className="font-semibold text-slate-800 mb-2">{label}</h4><ul className="space-y-2">{items.map(item)}</ul></div>)}</div>}
    {!!q.suggested_next_actions?.length && <div className="text-xs text-slate-600 border-t border-slate-100 pt-3"><h4 className="font-semibold text-slate-800 mb-2">Bước tiếp theo</h4><ul className="space-y-2">{q.suggested_next_actions.map(item)}</ul></div>}
    <p className="text-[10px] text-slate-400">Bộ kiểm tra {q.version || 'cũ'} · Tính lại phạm vi, phép tính và bằng chứng từ kết quả báo cáo</p>
  </section>;
};
